
name: Check & deploy API documentation
permissions:
  contents: write
  pull-requests: write
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  deploy-doc:
    if: ${{ github.event_name == 'push' }}
    name: Deploy API documentation on Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Deploy API documentation
        uses: bump-sh/github-action@v1.1.11
        with:
          doc: crawlora-com
          token: ${{ secrets.BUMP_TOKEN }}
          file: src/latest.yaml
  api-diff:
    if: ${{ github.event_name == 'pull_request' }}
    name: Check API diff on Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        
      - name: Comment pull request with API diff
        uses: bump-sh/github-action@v1.1.11
        with:
          doc: crawlora-com
          token: ${{ secrets.BUMP_TOKEN }}
          file: src/latest.yaml
          command: diff
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


    